
title:            杉亚的博客
description:      记录技术的点点滴滴.
disqus_shortname: 杉亚
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:              //sunzhuokai.github.io

# Owner/author information
owner:
  name:           Sunzhuokai
  avatar:         DSC_0504.jpg
  bio:            "一个伪装成程序员的光明料理界未来之星"
  email:          623326787@qq.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github: https://github.com/Sunzhuokai        
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +yourid

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter:    true
markdown:    kramdown
encoding: utf-8
# Amount of posts to show on home page
paginate: 5